ain:  ain x <Archive> <Directory>\
chz:  charc -e -p <Archive>
ha :  ha xy <Archive>
lim:  limit e -p <Archive>
pak:  pak e /Wp <Archive> <Directory>
sqz:  sqz x <Archive> <Directory>\
zip:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
rar:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
7z:   "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
arj:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
lzh:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
cab:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
tar:  "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
gz:   "$SV\sv_arc.cmd" "<Archive>" "<Directory>"
fb2:  "$SV\sv_fb2.cmd" "<Archive>" "<Directory>"
