# version.cmake -- счётчик номера сборки и ресурс версии.
#
# Номер сборки -- build/BUILD_NUMBER.txt, входит в историю. Увеличивает его
# cmake/build.cmake -- ровно один раз за запуск, так что все разрядности,
# собранные вместе, получают один номер. Отсюда же пересоздаются
# build/version.h и build/version.rc (без увеличения -- при первой настройке
# из CMakeLists.txt).
#
#   cmake -DSV_ROOT=<корень> [-DSV_BUMP=ON] -P cmake/version.cmake
#
# Версия продукта -- 4.0, как у авторской SV (S_U.PAS: Version = '4.0').

set(SV_VERSION_MAJOR 4)
set(SV_VERSION_MINOR 0)
set(SV_VERSION_PATCH 0)

function(sv_generate_version root bump)
    set(counter "${root}/build/BUILD_NUMBER.txt")
    set(build 0)
    if(EXISTS "${counter}")
        file(STRINGS "${counter}" lines LIMIT_COUNT 1)
        if(lines MATCHES "^([0-9]+)")
            set(build "${CMAKE_MATCH_1}")
        endif()
    endif()
    if(bump)
        math(EXPR build "${build} + 1")
        file(WRITE "${counter}" "${build}\n")
    endif()

    set(v "${SV_VERSION_MAJOR}.${SV_VERSION_MINOR}.${SV_VERSION_PATCH}")
    set(header "/* Generated by cmake/version.cmake -- do not edit. */
#ifndef SV_VERSION_H
#define SV_VERSION_H

#define SV_VERSION_MAJOR ${SV_VERSION_MAJOR}
#define SV_VERSION_MINOR ${SV_VERSION_MINOR}
#define SV_VERSION_PATCH ${SV_VERSION_PATCH}
#define SV_VERSION_BUILD ${build}
#define SV_VERSION_COMMA ${SV_VERSION_MAJOR},${SV_VERSION_MINOR},${SV_VERSION_PATCH},${build}
#define SV_VERSION_STRING \"${v}.${build}\"

#endif
")

    set(rc "/* Generated by cmake/version.cmake -- do not edit. */
#include <winver.h>
#include \"version.h\"

VS_VERSION_INFO VERSIONINFO
  FILEVERSION    SV_VERSION_COMMA
  PRODUCTVERSION SV_VERSION_COMMA
  FILEFLAGSMASK  VS_FFI_FILEFLAGSMASK
  FILEFLAGS      0
  FILEOS         VOS_NT_WINDOWS32
  FILETYPE       VFT_APP
  FILESUBTYPE    VFT2_UNKNOWN
BEGIN
  BLOCK \"StringFileInfo\"
  BEGIN
    BLOCK \"000004b0\"
    BEGIN
      VALUE \"CompanyName\",      \"Speaking Viewer\"
      VALUE \"FileDescription\",  \"Speaking Viewer\"
      VALUE \"FileVersion\",      SV_VERSION_STRING
      VALUE \"InternalName\",     \"SV\"
      VALUE \"OriginalFilename\", \"SV.exe\"
      VALUE \"ProductName\",      \"Speaking Viewer\"
      VALUE \"ProductVersion\",   SV_VERSION_STRING
    END
  END
  BLOCK \"VarFileInfo\"
  BEGIN
    VALUE \"Translation\", 0x0, 1200
  END
END
")

    foreach(pair "version.h|header" "version.rc|rc")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 name)
        list(GET pair 1 var)
        set(path "${root}/build/${name}")
        set(old "")
        if(EXISTS "${path}")
            file(READ "${path}" old)
        endif()
        if(NOT old STREQUAL "${${var}}")
            file(WRITE "${path}" "${${var}}")
        endif()
    endforeach()

    set(SV_VERSION_STRING "${v}.${build}" PARENT_SCOPE)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT SV_ROOT)
        get_filename_component(SV_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    endif()
    sv_generate_version("${SV_ROOT}" "${SV_BUMP}")
    message("${SV_VERSION_STRING}")
endif()
